INSERT INTO PRODUTO VALUES(30, 1, 'camisa');
INSERT INTO PRODUTO VALUES(12, 2, 'bola');
INSERT INTO PRODUTO VALUES(46, 3, 'caneca');
INSERT INTO PRODUTO VALUES(100, 4, 'fone de ouvido');
INSERT INTO PRODUTO VALUES(50, 5, 'short');
INSERT INTO PRODUTO VALUES(27, 6, 'tenis');
INSERT INTO PRODUTO VALUES(199, 7, 'paraquedas');

INSERT INTO CARRINHO VALUES (1);
INSERT INTO USERS VALUES (1, NULL, 1, 'gabriel@gmail.com', 'Gabriel', 'gabriel');

INSERT INTO CARRINHO VALUES (2);
INSERT INTO USERS VALUES (2, NULL, 2, 'lucas@gmail.com', 'Lucas', 'lucas');

INSERT INTO CARRINHO VALUES (3);
INSERT INTO USERS VALUES (3, NULL, 3, 'gabi@gmail.com', 'Gabi', 'gabi');

INSERT INTO CARRINHO VALUES (4);
INSERT INTO USERS VALUES (4, NULL, 4, 'raian@gmail.com', 'Raian', 'raian');

INSERT INTO CARRINHO VALUES (5);
INSERT INTO USERS VALUES (5, NULL, 5, 'rafael@gmail.com', 'Rafael', 'rafael');